from . import student_student
from . import student_admission
from . import student_parent
from . import student_teacher
from . import school_config
from . import academic_term
from . import academic_year
from . import student_timetable
from . import student_attendence
from . import exam_timetable
from . import exam_attendence
from . import result_template
from . import result_line
from . import marksheet_line
from . import marksheet_register
from . import teacher_assignment
from . import student_assignment
from . import fees_element
from . import fees_terms
from . import res_company
from . import hr
from . import student_fees