{
	'name': 'School Management',
	'category': '',
	'summary': 'School Management',
	'description': """School Management
	""",
	'version': '16.0.1',
	'depends': ['base',
				'mail',
				'website',
				'account',
				'calendar',
				'hr'],
	'data': [
		'security/security.xml',
		'security/ir.model.access.csv',
		'data/data.xml',
		'report/report_menu.xml',
		'report/student_idcard.xml',
		'report/student_marksheet.xml',
		'report/fees_analysis_report_view.xml',
		'report/student_attendence_report_view.xml',
		'report/report_timetable_student_generate.xml',
		'report/report_timetable_teacher_generate.xml',
		'report/student_hall_ticket_report.xml',
		'report/teacher_idcard.xml',
		'wizard/held_exam.xml',
		'wizard/student_attendence_view.xml',
		# 'wizard/fees_detail_report_wizard_view.xml',
		'wizard/generate_timetable.xml',
		'wizard/time_table_report.xml',
		'wizard/session_confirm.xml',
		'wizard/student_hall_ticket_wizard_view.xml',
		'views/student.xml',
		'views/standard.xml',
		'views/division.xml', 
		'views/admission.xml',
		'views/parent.xml',
		'views/teacher.xml',
		'views/subject.xml',
		'views/academic_term_view.xml',
		'views/academic_year_view.xml',
		'views/department.xml',
		'views/classroom.xml',
		'views/timing.xml',
		'views/timetable.xml',
		'views/attendance_sheet.xml',
		'views/attendance_line.xml',
		'views/attendance_register.xml',
		'views/exam.xml',
		'views/exam_session.xml',
		'views/exam_attendence.xml',
		'views/grade_config.xml',
		'views/result_template.xml',
		'views/result_line.xml',
		'views/marksheet_line.xml',
		'views/marksheet_register.xml',
		'views/student_assignment.xml',
		'views/teacher_assignment.xml',
		'views/teacher_inherit.xml',
		'views/student_inherit.xml',
		'views/student_fees_details_view.xml',
		'views/fees_element_view.xml',
		'views/fees_term_view.xml',
		'views/standard_inherit.xml',
		'views/hr_view.xml',
		'views/res_company.xml',
		# 'views/attendance_type.xml',
	],
	'demo': [
		'data/student.division.csv',
		'data/student.department.csv',
		'data/student.subject.csv',
		'data/student.class.csv',
		'data/student.classroom.csv',
		'data/cron_standard.xml',
		'demo/academic_year_demo.xml',
		'demo/academic_term_demo.xml',
		'demo/student_grade_configuration_demo.xml',
		'demo/product_category_demo.xml',
		'demo/product_demo.xml',
		'demo/student_fees_element_demo.xml',
		'demo/student_fees_terms_line_demo.xml',
		'demo/student_fees_terms_demo.xml',
		'demo/student_class_demo.xml',
		'demo/student_timing_demo.xml',
		'demo/student_exam_session_demo.xml',
		'demo/student_exam_demo.xml',
		'demo/student_result_template_demo.xml',
		'demo/student_marksheet_register_demo.xml',
	],
	'installable': True,
	'auto_install': False,
	'license': 'LGPL-3',
}
